{
 "title": "API Overview",
 "description": "A dashboard to monitor The Hive's backend using the RED method.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hive_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hive_http_requests_total{status_code=~\"5..\"}[5m])) / sum(rate(hive_http_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(hive_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(hive_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hive_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}